### ISSUE TITLE
Arduino IDE can't compile httpPost example

### ISSUE THREAD

**Issue by imaustink** [AprilBrother/cactus-micro#2]
I am trying to use one of your examples and Arduino can't even compile it:

Arduino: 1.6.1 (Mac OS X), Board: "LilyPad Arduino USB"

httpPost.ino:49:1: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:49:1: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:49:1: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino: In function 'bool connectWifi()':
httpPost.ino:94:50: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:94:50: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino: In function 'void setup()':
httpPost.ino:133:43: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:133:43: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:133:43: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino: In function 'void httpPost(String)':
httpPost.ino:194:57: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:194:57: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:205:39: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:205:39: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
httpPost.ino:205:39: error: converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)'
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by volca** [comment]
See #3. I think it will resolve your problem.

Please let me know if it works.

Best Regards.

**Comment by imaustink** [comment]
Still unable to compile the example:

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Mac OS X), Board: "Arduino Uno"
sketch_may04a.ino: In function 'void clearRx()':
sketch_may04a:38: error: 'Serial1' was not declared in this scope
sketch_may04a.ino: In function 'String readString(long int, String, String, String, String)':
sketch_may04a:55: error: 'Serial1' was not declared in this scope
sketch_may04a.ino: In function 'bool connectWifi()':
sketch_may04a:88: error: 'Serial1' was not declared in this scope
sketch_may04a.ino: In function 'void setup()':
sketch_may04a:103: error: 'Serial1' was not declared in this scope
sketch_may04a.ino: In function 'void httpPost(String)':
sketch_may04a:167: error: 'Serial1' was not declared in this scope

**Comment by volca** [comment]
You should choose board "LilyPad Arduino USB", not "Arduino UNO".

**Comment by imaustink** [comment]
Ah crap! I wasn't paying attention when I tried the older version! Sorry to bother you on that! It works now thank you! :)

**Comment by volca** [comment]
Good news!
