### ISSUE TITLE
Cactus micro won't connect to Wi-Fi

### ISSUE THREAD

**Issue by imaustink** [AprilBrother/cactus-micro#4]
I am unable to get the cactus micro to connect to my network with any example.

**Comment by volca** [comment]
ESP8266 can't support 5G. It only support 2.4G. What type is your Wi-Fi?

**Comment by imaustink** [comment]
It's a dual band router. 2.4 and 5Ghz are supported.

**Comment by volca** [comment]
What firmware revision is the esp-11 module?

You can type the AT commands to get this.

```
AT+GMR
```

**Comment by imaustink** [comment]
Could you write an example of how to do that?

**Comment by volca** [comment]
If you use SoftwareSerial, then download the [sketch](https://github.com/AprilBrother/cactus-micro/tree/master/examples/arduino/serialMonitor), otherwise download the [hardwareSerialMonitor.ino sketch](https://github.com/AprilBrother/cactus-micro/tree/master/examples/arduino/hardwareSerialMonitor).

Then you can input the AT commands in the serial monitor on Arduino IDE.

**Comment by imaustink** [comment]
Okay, I tried that and it doesn't respond.

**Comment by volca** [comment]
Which one did you try?

**Comment by imaustink** [comment]
I tied both examples provided.

**Comment by volca** [comment]
Do you have any other Wi-Fi spot?

**Comment by sscirrus** [comment]
Neither of those sketches are working for me either. It would be great if you could add a really simple sketch _just_ showing how to connect to WiFi.

**Comment by imaustink** [comment]
I have lot's of Wi-Fi sources. The cactus will not connect to any of them though.

To be real with you I have already accepted that the cactus micro does not function as advertised. I will be moving my project to DigiStump oaks after their release in October and I will develop on the Particle platform for now...

**Comment by sscirrus** [comment]
Thanks for your input @imaustink. It's frustrating (as a relative beginner) when the current documentation is so sparse.

**Comment by imaustink** [comment]
[Particle.io](https://www.particle.io/) sells the Photon for $20, ships this month. Take a look at their [API Docs](http://docs.particle.io/photon/api/) and behold their beauty.

**Comment by volca** [comment]
Cactus Micro is designed to use simple AT command to play Wi-Fi. I have tested on many Wi-Fi sources and works. Many buyers give me nice response about it.

I don't know which step you have played. Can u answer me some question?
- Did you upload the sketch successful?
- Did you see any log from the serial monitor?
- Can you show me which sketch you tested? And the the log message?

**Comment by imaustink** [comment]
Yes.
The serial monitor logged it was not connected. That's all.
I tried both examples provided.

**Comment by volca** [comment]
Hi,

Could you please try the sketch [httpPost.ino](https://github.com/AprilBrother/cactus-micro/blob/master/examples/arduino/httpPost/httpPost.ino)?

Please edit the SSID and pass. 

Run the sketch and give me a screenshot for the serial monitor.

Thank you.
