### ISSUE TITLE
Board resets when using external 12v to RAW

### ISSUE THREAD

**Issue by lorenwest** [AprilBrother/cactus-micro#5]
Hello, I very much enjoy working with the cactus micro 8266.  When powered by USB it works well, but when powering via 12v to RAW, it resets every few seconds.

The sketch I'm using is Blink.  When I use blink to power an LED on pin 3, it works fine until I power up the wifi on pin 13.  Once I issue the `digitalWrite(13,HIGH);`  the Arduino becomes unstable and resets the sketch every few seconds.

I have tried a 12v 1A power supply, and I have put it on my bench regulated power supply to see its only drawing between .05A and .1A @ 12V when the wifi board is enabled.

Is there special wiring I must do to use the external RAW pin with 12V?

Thank you,
-Loren

**Comment by volca** [comment]
A supply going into the ‘RAW’ pin will be regulated down to the correct operating voltage . To be safe, it shouldn’t be any higher than 12V, and it should be at least 1V more than 3.3V.

You can try with 9V or 5V external power.

**Comment by lorenwest** [comment]
I'll try with a lower voltage external power, but I was just wondering if this has been seen in other boards or if there was something I was missing. 

12V to RAW does regulate the board down to 3V3 as does putting 5V into the USB, but the difference is power to USB works fine powering the wifi, but 12v to raw makes it reset every few seconds.  Same sketch.

**Comment by volca** [comment]
Hi,

The LDO on Cactus Micro is [MIC5219](http://www.micrel.com/_PDF/mic5219.pdf). For 12V, it will be hot to reset. So I recommend the externa powerl voltage is 5V.

**Comment by lorenwest** [comment]
Yes, I turned the voltage on my bench power supply down to 10v and it stopped resetting.  My power supply is 12v (for another component in my system), so I'll install a voltage reducer before the arduino.

Thank you for your help!
