### ISSUE TITLE
Control Cactus Micro remotely in real time

### ISSUE THREAD

**Issue by sscirrus** [AprilBrother/cactus-micro#6]
Hi,

I would like to build a personal website so I can send my Cactus Micro new sketches via the internet and monitor what happens.

I know it can connect to a wireless network - assuming it is connected, how can I get it to accept a new sketch and run it straight away?

I assume that it may look something like this:
- The Cactus Micro connects to the network and gets a permanent address (how do I know what this is?).
- My site sends a POST request to that address with the new sketch (no problem).
- The Micro receives the sketch and immediately reboots, running the sketch (do I need to do anything special here or would this be the default reaction?).
- The sketch includes information requesting that certain data get sent back to my site (how might I program this in the sketch itself?).
- Huge bonus - can I get the Micro to run a new sketch WITHOUT having to send it the wifi network name and password every time? This would be a security vulnerability, obviously.

Any pointers you can give me to help me figure out the critical stuff would be most helpful. I apologize that the question is broad but there seems to be so little info out there on the Micro.

Thank you!

**Comment by volca** [comment]
Looks like you want upload new sketch via Wi-Fi network. I think it's not easy for Cactus Micro. It need virtual usb-to-serial port to upload sketch. I have no idea for this currently.

I think you should try play [NodeMCU](http://nodemcu.com/). You can write code in lua and it's very easy to be upgraded by wireless network. The module esp-11 is a start point.

**Comment by sscirrus** [comment]
Would it be possible to install Autobahn|JS on the Cactus so I can connect via WAMP/Websprockets?

**Comment by volca** [comment]
No. You can't. Cactus Micro is a Arduino Clone project. Not a micro computer.
