### ISSUE TITLE
ESP Firmware

### ISSUE THREAD

**Issue by flyandi** [AprilBrother/cactus-micro#7]
I want to upload my own Firmware. I saw that you guys exposed all the ESP pins on the REV1 version but not on REV2. Can you give me instructions how to upload the firmware now?

**Comment by volca** [comment]
Hi,

Please refer [How to made Cactus Micro R2 as ESP8266 programmer](http://wiki.aprbrother.com/wiki/How_to_made_Cactus_Micro_R2_as_ESP8266_programmer)
