### ISSUE TITLE
searchBaudRate example problem (destroyed board)

### ISSUE THREAD

**Issue by webwarecz** [AprilBrother/cactus-micro#8]
Hi All,

after uploading (by old IDE 1.0.6) example "searchBaudRate.ino" to Cactus Micro REV2, board from this time permanently reset:-(. Windows environment, USB 2.0. In device management i see every +-5s  ON/OFF "Arduino LilyPad USB bootloader" (not "Arduino LilyPad USB" (!)).
- short press reset button not correct this situation
- long press reset button not correct this situation
- long power off not correct this situation
- new (other) sketch is unable load to board

Any idea?:-(

thanks for info
BJ

**Comment by volca** [comment]
Where did you buy the board? We can send a replace one to you. Please contact our sales from where you bought the board.

Thank you.

**Comment by webwarecz** [comment]
I buy this modul on ebay (no directly from "AprilBrother", but "camealone" seller:-(). Thanks for info, I contact our sales.

Second idea, I have original ISP modul from Arduino:
"https://www.arduino.cc/en/Main/ArduinoISP"
...maybe replace bootloader correct this situation, but on "Cactus Micro Rev2" board not 6pin ISP connector, like e.g. on "Arduino nano" ...exists schema for connect ISP to "Cactus Micro Rev2"?

thanks for info
BJ

**Comment by volca** [comment]
The "camealone" seller is one of our sellers. Please contact him and refer this page.

Thank you.
